# -*- coding: utf-8 -*-
"""Copy of Trips-Trraps_Trull.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytRPklgWvHSqg9JPf107eCTyug-Q0azi
"""

#Two Player "Trips-Traps-Trull" game in Python

theBoard = {'7': ' ' , '8': ' ' , '9': ' ' ,
            '4': ' ' , '5': ' ' , '6': ' ' ,
            '1': ' ' , '2': ' ' , '3': ' ' }

board_keys = []

for key in theBoard:
    board_keys.append(key)

def printBoard(board):
    print(board['7'] + '|' + board['8'] + '|' + board['9'])
    print('-+-+-')
    print(board['4'] + '|' + board['5'] + '|' + board['6'])
    print('-+-+-')
    print(board['1'] + '|' + board['2'] + '|' + board['3'])

# gameplay functionality follows
def game():

    turn = 'X'
    count = 0

    for i in range(10):
        printBoard(theBoard)
        print("SINU KORD," + turn + " VALI RUUT")

        move = input()        

        if theBoard[move] == ' ':
            theBoard[move] = turn
            count += 1
        else:
            print("RUUT HÖIVATUD!\nVALI RUUT")
            continue

        # check if either player has won, after every 5 moves
        if count >= 5:
            if theBoard['7'] == theBoard['8'] == theBoard['9'] != ' ': # across the top
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")                
                break
            elif theBoard['4'] == theBoard['5'] == theBoard['6'] != ' ': # across the middle
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break
            elif theBoard['1'] == theBoard['2'] == theBoard['3'] != ' ': # across the bottom
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break
            elif theBoard['1'] == theBoard['4'] == theBoard['7'] != ' ': # down the left side
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break
            elif theBoard['2'] == theBoard['5'] == theBoard['8'] != ' ': # down the middle
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break
            elif theBoard['3'] == theBoard['6'] == theBoard['9'] != ' ': # down the right side
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break 
            elif theBoard['7'] == theBoard['5'] == theBoard['3'] != ' ': # diagonal
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break
            elif theBoard['1'] == theBoard['5'] == theBoard['9'] != ' ': # diagonal
                printBoard(theBoard)
                print("\nMÄNG LÄBI.\n")                
                print(" **** " +turn + " VÕITIS! ****")
                break 

        # If neither player wins, result as 'VIIK!'
        if count == 9:
            print("\nMÄNG JÄI VIIKI!.\n")                
            print("VIIK!!!")

        # player change after every move
        if turn =='X':
            turn = 'O'
        else:
            turn = 'X'        
    
    # question: rematch or go home
    restart = input("MÄNGIME UUESTI? (JAH / EI)")
    if restart == "j" or restart == "e":  
        for key in board_keys:
            theBoard[key] = " "

        game()

if __name__ == "__main__":
    game()